name: C CI

on: [push, pull_request]

jobs:          
  analyzing-code:
    runs-on: self-hosted
    name: A job to check for vulnerabilities
    steps:
      - name: Simple test action
        id: docker
        uses: shovon0203/docker-action@main
        with:
          who-to-greet: 'Shovon!'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run modification script
        run: |
          FILENAME="hello.c"
          echo "Appending function to $FILENAME"
          cat <<EOT >> $FILENAME
          void newFunction() {
            printf("Appended Code");
          }
          EOT
      - name: Ensure dpkg is configured correctly
        run: sudo dpkg --configure -a

      - name: Track wget usage
        run: |
          echo "Running wget to download example file"
          wget https://file-examples.com/wp-content/storage/2017/10/file-sample_150kB.pdf
      - name: Track curl usage
        run: |
          echo "Running curl to fetch example data"
          curl https://example.com/
      - name: Uninstall htop
        run: |
          echo "Uninstalling htop"
          sudo apt-get remove -y htop
      - name: Install htop
        run: |
          echo "Installing htop"
          sudo apt-get install -y htop

      - name: Set up build environment
        run: sudo apt-get install -y gcc make
      - name: Build
        run: make
      - name: Test executable
        run: ./hello
    outputs:
      suspicious_activity: ${{ env.SUSPICIOUS_ACTIVITY }}
      
  run-code:
    runs-on: ubuntu-latest
    needs: analyzing-code
    steps:
    - name: Manual approval
      if: needs.analyzing-code.outputs.suspicious_activity == 'true'
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: shovon0203
    - name: Simple test action
      id: docker
      uses: shovon0203/docker-action@main
      with:
        who-to-greet: 'Shovon!'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run modification script
      run: |
          FILENAME="hello.c"
          echo "Appending function to $FILENAME"
          cat <<EOT >> $FILENAME
          void newFunction() {
            printf("Appended Code");
          }
          EOT
    - name: Ensure dpkg is configured correctly
      run: sudo dpkg --configure -a
    - name: Set up build environment
      run: sudo apt-get install -y gcc make
    - name: Build
      run: make
    - name: Test executable
      run: ./hello
