name: C CI

on: [push, pull_request]

jobs:                
  run-code:
    runs-on: ubuntu-latest
    steps:
    - name: Step security
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit
    - name: Simple test action
      id: docker
      uses: shovon0203/docker-action@main
      with:
        who-to-greet: 'Shovon!'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up build environment
      run: sudo apt-get install -y gcc make
    - name: Build
      run: make
    - name: Test executable
      run: ./hello
